### ISSUE TITLE
Error in integration test- S3DirectoryLockITest

### ISSUE THREAD

**Issue by AlJohri** [albogdano/lucene-s3directory#2]
I pulled down the latest code from e4a1613f3de2b6641de7d367828012e0e1fbbbfd and ran `mvn integration-test` and got 1 failure. Not sure if this is expected, or a test that succeeds intermittently, or if I need to change some configuration on the S3 side to make this work?

Here are the logs:

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.133 s <<< FAILURE! - in com.erudika.lucene.store.s3.S3DirectoryLockITest
[ERROR] testLocks(com.erudika.lucene.store.s3.S3DirectoryLockITest)  Time elapsed: 0.133 s  <<< ERROR!
org.apache.lucene.store.LockObtainFailedException: Lock object could not be created:
	at com.erudika.lucene.store.s3.S3DirectoryLockITest.testLocks(S3DirectoryLockITest.java:52)
Caused by: software.amazon.awssdk.services.s3.model.NoSuchBucketException: The specified bucket does not exist (Service: S3, Status Code: 404, Request ID: 1BAPQ9CVRZGBSC1D, Extended Request ID: 5HpZ+1n+sy2tlW6I9hZf1JgGebrhCo6zpYcTGGJxmxlgxidsO5AaVN7VsyeKtREkVs/PjtfBP90=)
	at com.erudika.lucene.store.s3.S3DirectoryLockITest.testLocks(S3DirectoryLockITest.java:52)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   S3DirectoryLockITest.testLocks:52 » LockObtainFailed Lock object could not be ...
[INFO]
[ERROR] Tests run: 25, Failures: 0, Errors: 1, Skipped: 0
```

I'm not relying on the writing/locking features at this time so this doesn't effect me but just wanted to let you know.

**Comment by albogdano** [comment]
Looks like a flaky test to me. Try building it with `-DskipTests=true`.
Any success with the updated version?
